### ISSUE TITLE
Make clear clearStaleData method optional on save instance state

### ISSUE THREAD

**Issue by marcaoas** [livefront/bridge#11]
When using a view pager or other libraries like [this one](https://github.com/JetradarMobile/android-multibackstack) the instance of the fragment i lost and when that happens the instance state saved on from bridge is cleared on the next `onSaveInstanceState` call. Would be great if the `BridgeDelegate.clearStaleData` call on the `Bridge.onSaveInstanceState` could be optional.

**Comment by byencho** [comment]
Sure I'll look into an update soon where I either make that feature optional or just remove it entirely (since it's a bit redundant if you use `Bridge.clear()` anyway).

**Comment by byencho** [comment]
@marcaoas In the `v1.1.2` release I've removed the automatic data clearing entirely. Please check that this resolves your issue. Also note that you might need to reassess which `Fragment` instances you use `Bridge.clear()` in. See https://github.com/livefront/bridge/issues/17 for more details.

**Comment by marcaoas** [comment]
Ok @byencho I updated to v1.1.2 and everthing seems is working. 
Thank you.

**Comment by byencho** [comment]
@marcaoas Great, thanks for letting me know! I'm going to close this issue now.
