### ISSUE TITLE
Still facing the problem

### ISSUE THREAD

**Issue by vaibhav-droid** [livefront/bridge#12]
Hey, I have used both and bridge and Icepick but still getting the error. I have initialized bridge in Application class and then in my activity class I have a fragment pager adapter and for that fragment, I have used restore and save methods but as soon as I am putting my application in the background it gets crashed because of transition too large exception.
Any other help on this if I am missing something related to FragmentPagerAdapter.
I have also tried saveState approach for the adapter but no success.

**Comment by byencho** [comment]
Could you paste an example of how you are using Bridge in one your Fragment classes? If you're using Bridge, the only place your Icepick calls should appear are when initializing Bridge, so I just want to make sure you're not _also_ calling it when you call the Bridge save / restore methods.

**Comment by byencho** [comment]
@vaibhav-droid Unless you can provide more detailed information I'm going to close this issue.
