### ISSUE TITLE
Failed to resolve: com.github.livefront:bridge:v1.1.3

### ISSUE THREAD

**Issue by gilromeu** [livefront/bridge#27]
When running the gradle this error occurs

![image](https://user-images.githubusercontent.com/6742585/50300897-92581e80-0464-11e9-8152-e33d34f4cddd.png)

**Comment by gilromeu** [comment]
To find the error, I include

repositories {
maven {url "https://jitpack.io"}
}
however it should be included in

allprojects {
maven {url "https://jitpack.io"}
}

**Comment by byencho** [comment]
Well technically I think its supposed to be

```gradle
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

See https://jitpack.io/ . I might need to update the docs to make that more clear.
