### ISSUE TITLE
Bridge always need android state library to support with

### ISSUE THREAD

**Issue by AparnaKS** [livefront/bridge#35]
I am not using any android state library like icepick as saved state handler. But was directly keeping data to bundle using putParcelable, putByteArray etc. In this case how to use bridge library. I have integrated your library and for test purpose added data to bundle (like savedInstanceState.putByteArray("bytes", new byte[1000 * 1000]);)  and have used Bridge to save my bundle eg Bridge.saveInstanceState(this, savedInstanceState);

When i checked the log i am still getting TransactionTooLargeException

**Comment by AparnaKS** [comment]
Adding to the above, my writetodisk method  is not executing as the bundle is null. Please suggest

 Bundle bundle = new Bundle();
        mSavedStateHandler.saveInstanceState(target, bundle);
        if (bundle.isEmpty()) {
            // Don't bother saving empty bundles
            return;
        }

**Comment by byencho** [comment]
Hi @AparnaKS . So this question was asked before here : https://github.com/livefront/bridge/issues/14 . There's a suggestion there for how to do this without a library like `Icepick`, but in the end your best option is just use something like Icepick.

**Comment by byencho** [comment]
The key idea here is that `Bridge` is constructed in a way such that given an object, your `SavedStateHandler` is responsible for adding data to the `Bundle`. It simply does not support directly adding data to the `Bundle` in the way you are suggesting. As suggested in https://github.com/livefront/bridge/issues/14#issuecomment-393617407 , using a new interface could allow you to manually add data, but still not quite in the way you are trying to do. You can refer to the sample app for correct usage.

**Comment by AparnaKS** [comment]
Thanks for the quick response. It worked with custom StateManager interface. Thank you so much @byencho

**Comment by byencho** [comment]
No problem, @AparnaKS! Glad to help.
