### ISSUE TITLE
How to store/retrieve custom ArrayList object which we use for recyclerview ?

### ISSUE THREAD

**Issue by AbuzarJan** [livefront/bridge#47]

**Comment by byencho** [comment]
That all depends on what you are using as your `SavedStateHandler`. If you calling into something like https://github.com/evernote/android-state , then you'd do something like this:

```kotlin
@State 
var dataList: ArrayList<Data> = ArrayList()
```

where `Data` (or whatever your model would be) is required to be `Parcelable`.

**Comment by byencho** [comment]
@AbuzarJan I'm going to close this issue. Let me know if there are still questions about it. Take a look at the sample, too, if you are just having issues getting `Bridge` set up.
