### ISSUE TITLE
android.preference library is deprecated

### ISSUE THREAD

**Issue by mrtry** [livefront/bridge#57]
`android.preference`  is deprecated as of Android 10. 😭 
Do you plan to migrate?
see: https://developer.android.com/about/versions/10/behavior-changes-all#preferences

**Comment by mrtry** [comment]
Sorry, I confused `android.preference` and `android.content.SharedPreferences`

**Comment by byencho** [comment]
No problem. Even though what you mentioned isn't related I'll note that I'm actually probably going to migrate away from `SharedPreferences` at some point anyway to resolve https://github.com/livefront/bridge/issues/48 .
