### ISSUE TITLE
Google Play is flagging the GET_TASKS permission as an error in the pre-launch report when supporting Android 4.4 and below

### ISSUE THREAD

**Issue by Kisty** [livefront/bridge#59]
Hi there! Thanks for this library, it's helped a lot.

We had to add the GET_TASKS permission as it's required to use the `getRunningTasks()` for Android 4.4 and below else it crashes. I don't think there's a way to add the permission for only devices running Android 4.4 and below. https://github.com/livefront/bridge/blob/e0c4e6551ba93e877adcf58737168089f0c6c821/bridge/src/main/java/com/livefront/bridge/BridgeDelegate.java#L167

We're about to publish a release but the Google Play pre-launch report but it's flagged an error.

> Your app is requesting permissions which are used by less than 1% of functionally similar apps:
> 
> android.permission.GET_TASKS
> Users prefer apps that request fewer permissions and requesting unnecessary permissions can affect your app's visibility on the Play Store. If these permissions aren't necessary, you may be able to use alternative methods in your app and request fewer permissions. If they are, we recommend providing an explanation to users of why you need the permissions.
> 
> Note: This guidance is based on a comparison with functionally similar apps, which change over time as new apps get published and existing apps change behavior. Therefore the warning may change even if you don't change your permission usage.

We can explain the reason behind this but it could be a privacy concern for our users.

1. What's the GET_TASKS permission for?
1. Is the GET_TASKS permission necessary?
3. Is there another way we can do it so to remove the permission?

**Comment by byencho** [comment]
Hi @Kisty . So this all relates to how `Bridge` actively clears data on fresh loads of an app. Due to some edge cases, determining a "fresh state" is a bit more complicated than originally intended and we now need to check for running app process data to see if there is only one `Activity` associated with you app when the check is made. The call to `activityManager.getRunningTasks(1)` is necessary to do so pre-M. 

I agree that it's unfortunate that you seem to be required to add `GET_TASKS` to support Android 4.4 and below. I was not aware of that when [the PR for that change](https://github.com/livefront/bridge/pull/50) was merged unfortunately as it is not part of the [official documentation](https://developer.android.com/reference/android/app/ActivityManager#getRunningTasks(int)). At minimum I would have added a warning to the README, which I will likely do soon now.

The only way I can think of getting around the requirement for most of your users would be to:
- try to split up your APK into a 4.4-and-under variant that has the flag and another for everyone else. This is definitely a hassle but its possible in theory and Google Play allows it.
- Skip using `Bridge` for users 4.4-and-under and call straight to your `SavedStateHandler` instead. This should work just fine because the crash that `Bridge` solves wasn't introduced until Android Nougat anyway.

Let me know if that helps.

**Comment by Kisty** [comment]
Thanks for this, @byencho. That's great. What I've done for now is put a `android:maxSdkVersion="19"` on the `android.permission.GET_TASKS` permission which only applies the permission for 4.4 and below.

When you say I can call straight in to `SavedStateHandler` directly, does that mean that for 4.4 and below, I can skip the entire `Bridge` set up? E.g.

`App.java`
```
    @Override
    public void onCreate() {
        savedStateHandler = new SavedStateHandler() {
            @Override
            public void saveInstanceState(@NonNull Object target, @NonNull Bundle state) {
                if (target instanceof StateManager) {
                    ((StateManager) target).saveState(state);
                }
            }

            @Override
            public void restoreInstanceState(@NonNull Object target, @Nullable Bundle state) {
                if (target instanceof StateManager) {
                    ((StateManager) target).restoreState(state);
                }
            }
        };
        if (Build.VERSION.SDK_INT <= Build.VERSION_CODES.KITKAT) {
            Bridge.initialize(this, savedStateHandler);
        }
    }
```

Then in `MyActivity.java`
```
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.restoreInstanceState(this, savedInstanceState);
        } else {
            ((MyApplicationBase) getApplication()).getSavedStateHandler().restoreInstanceState(this, savedInstanceState);
        }
        ...
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.saveInstanceState(this, outState);
        } else {
            ((MyApplicationBase) getApplication()).getSavedStateHandler().saveInstanceState(this, outState);
        }
    }
```

I use the solution for saving state using no annotation processor but the one outlined in this question #14

**Comment by byencho** [comment]
@Kisty That's roughly the idea, yes. It looks like you might have the version check in the Application switched around though. I would probably tweak it a bit too:

In the Application:

```java
    @Override
    public void onCreate() {
        // This should be done for all versions above KitKit, not below (compare to your example)
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            // You can just initialize the handler here since you don't need to save it as a variable.
            SavedStateHandler savedStateHandler = ...;
            Bridge.initialize(this, savedStateHandler);
        }
    }
```

In an Activity:

```java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.restoreInstanceState(this, savedInstanceState);
        } else {
            // Call your restore method directly here
            restoreInstanceState(this, savedInstanceState);
        }
        ...
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.saveInstanceState(this, outState);
        } else {
            // Call your saved method directly here
            saveInstanceState(this, outState);
        }
    }
```

Assuming the `restoreInstanceState` / `saveInstanceState` are on some Activity base class, you can call those directly. And even if you were using `StateSaver` this would still just be:

```java
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.restoreInstanceState(this, savedInstanceState);
        } else {
            StateSaver.restoreInstanceState(this, savedInstanceState);
        }
        ...
    }

    @Override
    protected void onSaveInstanceState(@NonNull Bundle outState) {
        super.onSaveInstanceState(outState);
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) {
            Bridge.saveInstanceState(this, outState);
        } else {
            StateSaver.saveInstanceState(this, outState);
        }
    }
```

So you don't need to literally grab the reference to your `SavedStateHandler` from your Application; I just meant that could directly call whatever you were using to implement your `SavedStateHandler` wherever you would normally call `Bridge`. I hope this all works out for you!

**Comment by 7Koston** [comment]
Just
`    <uses-permission
        android:name="android.permission.GET_TASKS"
        android:maxSdkVersion="20" />
`
In AndroidManifest.xml

**Comment by Kisty** [comment]
Thanks for your help. I think this has resolved it. Cheers!

**Comment by byencho** [comment]
Sure thing 👍 Glad we came up with something acceptable to get around the problem.
